// tailwind.config.js
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    spacing: {
      px: "1px",
      0: "0",
      0.5: "0.125rem",
      1: "0.25rem",
      1.5: "0.375rem",
      2: "0.5rem",
      2.5: "0.625rem",
      3: "0.75rem",
      3.5: "0.875rem",
      4: "1rem",
      5: "1.25rem",
      6: "1.5rem",
      7: "1.75rem",
      8: "2rem",
      9: "2.25rem",
      10: "2.5rem",
      11: "2.75rem",
      12: "3rem",
      14: "3.5rem",
      16: "4rem",
      20: "5rem",
      24: "6rem",
      28: "7rem",
      32: "8rem",
      36: "9rem",
      40: "10rem",
      44: "11rem",
      48: "12rem",
      52: "13rem",
      56: "14rem",
      60: "15rem",
      64: "16rem",
      72: "18rem",
      80: "20rem",
      96: "24rem",
    },
    extend: {
      colors: {
        'primary-brown': 'var(--primary-brown)',
        'secondary-brown': 'var(--secondary-brown)',
        'third-brown': 'var(--third-brown)',
        'primary-green': 'var(--primary-green)',
        'secondary-green': 'var(--secondary-green)',
        'neutral-white': 'var(--neutral-white)',
      },
    },
  },
  plugins: [
    function({ addBase }) {
      addBase({
        // Ajouter des règles CSS personnalisées pour les classes gap et margin
        '.gap-1': { gap: '0.25rem' },
        '.gap-2': { gap: '0.5rem' },
        '.gap-3': { gap: '0.75rem' },
        '.gap-4': { gap: '1rem' },
        '.gap-5': { gap: '1.25rem' },
        '.gap-6': { gap: '1.5rem' },
        '.gap-8': { gap: '2rem' },
        '.gap-10': { gap: '2.5rem' },
        
        '.mb-1': { marginBottom: '0.25rem' },
        '.mb-2': { marginBottom: '0.5rem' },
        '.mb-3': { marginBottom: '0.75rem' },
        '.mb-4': { marginBottom: '1rem' },
        '.mb-5': { marginBottom: '1.25rem' },
        '.mb-6': { marginBottom: '1.5rem' },
        '.mb-8': { marginBottom: '2rem' },
        '.mb-10': { marginBottom: '2.5rem' },
        
        '.mt-1': { marginTop: '0.25rem' },
        '.mt-2': { marginTop: '0.5rem' },
        '.mt-3': { marginTop: '0.75rem' },
        '.mt-4': { marginTop: '1rem' },
        '.mt-5': { marginTop: '1.25rem' },
        '.mt-6': { marginTop: '1.5rem' },
        '.mt-7': { marginTop: '1.75rem' },
        '.mt-8': { marginTop: '2rem' },
      })
    }
  ],
}
