-- Insertion de 50 races de chiens populaires
INSERT INTO race (name) VALUES
('Labrador Retriever'),
('Berger Allemand'),
('Golden Retriever'),
('Bouledogue Français'),
('Beagle'),
('Caniche'),
('Rottweiler'),
('Yorkshire Terrier'),
('Boxer'),
('Teckel'),
('Berger Australien'),
('Cavalier King Charles'),
('Shih Tzu'),
('Doberman'),
('Husky Sibérien'),
('Chihuahua'),
('Bulldog Anglais'),
('Épagneul Breton'),
('Border Collie'),
('Jack Russell Terrier'),
('Cocker Spaniel'),
('Setter Anglais'),
('Berger Belge Malinois'),
('Staffordshire Bull Terrier'),
('Bichon Frisé'),
('Bouvier Bernois'),
('Dalmatien'),
('Terre-Neuve'),
('Saint-Bernard'),
('Akita Inu'),
('Shiba Inu'),
('Basset Hound'),
('West Highland White Terrier'),
('Berger des Shetland'),
('Bull Terrier'),
('Lhassa Apso'),
('Rhodesian Ridgeback'),
('Samoyède'),
('Schnauzer'),
('Whippet'),
('Boston Terrier'),
('Cairn Terrier'),
('Chow Chow'),
('Coton de Tuléar'),
('Fox Terrier'),
('Lévrier Afgahn'),
('Pékinois'),
('Pinscher Nain'),
('Shar Pei'),
('Welsh Corgi');
